version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db-postgres:
    image: postgres:16-alpine
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - app-network
  app:
    depends_on:
      - db-postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network

volumes:
  db:
